<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DatabaseSeeder extends Seeder
{
    use WithoutModelEvents;

    public function run(): void
    {
        DB::statement('SET session_replication_role = replica');

        DB::table('project_terminal_sessions')->truncate();
        DB::table('project_code_comments')->truncate();
        DB::table('project_tasks')->truncate();
        DB::table('project_invitations')->truncate();
        DB::table('project_participants')->truncate();
        DB::table('notifications')->truncate();
        DB::table('registration_verifications')->truncate();
        DB::table('personal_access_tokens')->truncate();
        DB::table('projects')->truncate();
        DB::table('admins')->truncate();
        DB::table('users')->truncate();

        DB::statement('SET session_replication_role = origin');

        $this->seedUsers();
        $this->seedAdmin();
        $this->seedProjects();
        $this->seedParticipants();
        $this->seedInvitations();
        $this->seedNotifications();
        $this->seedCodeComments();
        $this->seedTasks();
        $this->seedTerminalSessions();

        $this->resetSequences();
    }

    private function seedUsers(): void
    {
        $users = [
            [
                'user_id' => 1,
                'name' => 'xolodilov06@mail.ru',
                'email' => 'xolodilov06@mail.ru',
                'password_hash' => '$2y$12$iAQYWP9JXm/OiP2JTOMnXeAV7L7uuZir1VyELd9vqM.TcZ4KPsnGO',
                'status' => 'active',
                'language' => 'rus',
                'theme' => 'light',
                'avatar_type' => 'upload',
                'avatar_preset' => 'robot',
                'avatar_path' => 'avatars/1/avatar-1781494028-ELVjV8QdpI4c.png',
                'forgejo_user_id' => 1,
                'forgejo_username' => 'chingazin',
                'forgejo_access_token' => 'eyJpdiI6Im1pWjZza2FoN2VRa3hZdFZGYnBBQUE9PSIsInZhbHVlIjoiVnd1S1lGM0NxVFA0NGRmWDl0Njc5Y3I2NnNOWUFBZU94QjFNUXNESkJxazRLSjFFOUVGdU9vNUxRY2dlYmNja3RJMVZnTjhCbTNVVTB1RUFidUMza2l3N0JKWkEvSElJY2hOZ0xTU1Q5RGkzeGpXbDljeWpMRWdJa2hzc2Y5M0RrVVZtZUg4OVFuNzZCMW9hdG5aOHlMbVpzRXhmYUpLN1NjRE5UUG5ub1lXdFp6ekpleTZmWEN3bnZvWGN6OGZUbFlHcko4YWFMZzYvcUNEYTNmS2hVVkZlWCtTRzNGSm9palRwOUlqR0hEcVRKTHduREo2ZWxoNU5sTkJya091TkpHeGp5ZGk0dWJUR2ZHcm9Ed0Zpa3Q0V0lhbFRzQkVDTjJaeHRUZlBwN2o2ZDVMdE0zT2lad2g4Z094S0dYVmlHYmZMalJHRklVMTYyVGxyWkx1S0lRMjlPdW4yUWNrQWRrUzFadldhZVZNYmYzZlZ1RXEzYkpRTTYxdUhnVzdNejhRU0VmczBxV1NsV1o3NnNzYWp4T0JMckJzVldEaFJ5eUhMaDhxaFZNd0Y2bGdYWnluaTZPZVVzeFhOLzlWTUtOTytYUkZpd1p6RytrVGYrMWw2Nm9lMHJSOXFQNDlLZkIxRUVqM0pmeUZ2K2QxQUhnZVJ5QjZUc1Y0cnlla2VnSFFwM1BWVDc1NHkySVpCa3ZNQUt2ZkM5RXFmT01sTjRUSkh5SU9QVkdScDVxQVB1c1EyUmN5cm1HYXNXckpYNlFVU0dScG9xTFYwbndLM0o4YTlJTG5FdkYzb1hjNDBXbDYvWUJOamhoQnhhNWtneS9PT3pNMEZYOFM2MFc2czdWdkpTZFhPcFNQK2JQRVIrcXNjVSt5UTlxdXcyd0pLRVh2K0x3SEVrT0JlbHJxYXlONDVXNHc4RXp5RitHZDYiLCJtYWMiOiJkYTgyODg2Yjk2OGQyMGU1M2MzMzg3ZTBkODNhMGY3YTRjMTc3MWQ1OTQ0NGNhOGQzZTc3Mjc4MGM1MmE3OGQ0IiwidGFnIjoiIn0=',
                'forgejo_refresh_token' => 'eyJpdiI6IlZGbVR6VGwvQmFIUFQ2YzNqQXJIWmc9PSIsInZhbHVlIjoiWmVRZFpPN0F5V1kyWVFQNEhLZTduUXlEY0hxMEc5MS9GamJMWUpjZHFFVmtPak9QWE9kcFBVZWhqeGdGVHZvS2tJbHE3V3BSNkZZeFJYaHFVYUVzK2oyZFEremJOOENTdGhpU2hXL3BBNzZINXkyS0JJc0QyZER2WmFraTdWQVplRjdlYkdGZlZVT3ZEMWUyTmVsZ1l1dklCNWJCMDZXeTJsUEoyQ25jZVJGTTdLWFlmSnF5UGtONWlLblV1NkU3dytaUWRtWFdIb0NPMTA5V2ZlWGgrSSs3dzB5R0dDc2hVa2dOZU1VYVlUMXpJUUZydjN6L25DdFlkdm81QW9YSk5MMEJGMHV1NlVKMGIwZ1FXbkZ5NEg2N3pOMWRjNTFWTHo0c1ZFUEtJTHF5OXBWOU9iYWJ0dTFEVW9HTWJyeVcxZkZLUWFwc2xMMnoxUzJlMG0wOWxnc1NVMlZmQTYyK0w5TDlJaUt2OFRiR1FNbWJ1TkJDVVlHdGhXTW56NWoyRFFqZG90MW9hZ1BkSjdHTG40K3JKYmNBaG9IYStLQ3cwV2ZQd2VBSUkyWFBLQnF6dU9DY0FPRi94MmV1SWRvaFpwMTAzSzhSRjhpRGF1SlhlWlpPRXNzTWxJZXlodXNCcWxDdjBvbUtNV3NDRjN1K1V5Y2sycjI3MFBZWmZlTGxNNk40RGc0QUk5WklOV0pVYjdhOFdGUE9lUWFIQm1ickt6aXE1YWE3V2wwNGZLZnVzZ3lKVEtLUjhIbnc3eC81UXpJWGxYdnFVSUI4dWxiemZ1aERlcXVnV041cEFSK3p1SVBZMlVpang3aENXMzVQSjlpOEV0ME5yVk9DRzBoMzRIOFNyM01OZnFXUWo2Q3NDSXMxSUlTUUFUVkVBRFJ0OUZEY1FLNE9hd2swVzdnd0hWYVVoT3pXWGVIN1V2bzlZbEIzdHdXZ0U5T2VybnUvOFFzQVhBPT0iLCJtYWMiOiJhZjcxNjc5NWM4NzEzYjEyYTE5NGU2ZTk3Y2EzNDYzMWZmN2M0ZmU4NjFiZTk1Y2FhNDA2Y2ViMWU2YjhmNzFkIiwidGFnIjoiIn0=',
                'forgejo_token_expires_at' => '2026-06-15 08:22:35',
                'forgejo_connected_at' => '2026-06-15 07:22:35',
                'last_seen' => null,
                'created_at' => '2026-04-13 16:39:13',
                'updated_at' => '2026-06-15 14:22:35',
            ],
            [
                'user_id' => 2,
                'name' => 'goitskolaprogrammirovania@gmail.com',
                'email' => 'goitskolaprogrammirovania@gmail.com',
                'password_hash' => '$2y$12$HEw1ryCEqNRvdGxiFyiSS.KP/yjzEEMGLUwEEgJ0Nnwuf2/mIQY8m',
                'status' => 'active',
                'language' => 'rus',
                'theme' => 'system',
                'avatar_type' => 'preset',
                'avatar_preset' => null,
                'avatar_path' => null,
                'forgejo_user_id' => null,
                'forgejo_username' => null,
                'forgejo_access_token' => null,
                'forgejo_refresh_token' => null,
                'forgejo_token_expires_at' => null,
                'forgejo_connected_at' => null,
                'last_seen' => null,
                'created_at' => '2026-04-14 07:51:00',
                'updated_at' => '2026-04-14 07:51:00',
            ],
            [
                'user_id' => 3,
                'name' => 'Priscilla Kulas',
                'email' => 'lgrimes@example.org',
                'password_hash' => '$2y$12$MyMdefmMyn8YL2USYQPLn..A8LxXxk60cxxLs3mLB6X5KhPiA7OKW',
                'status' => 'active',
                'language' => 'rus',
                'theme' => 'system',
                'avatar_type' => 'preset',
                'avatar_preset' => null,
                'avatar_path' => null,
                'forgejo_user_id' => null,
                'forgejo_username' => null,
                'forgejo_access_token' => null,
                'forgejo_refresh_token' => null,
                'forgejo_token_expires_at' => null,
                'forgejo_connected_at' => null,
                'last_seen' => null,
                'created_at' => '2026-04-23 04:39:18',
                'updated_at' => '2026-04-23 04:39:18',
            ],
            [
                'user_id' => 4,
                'name' => 'Dr. Antonetta Hagenes Jr.',
                'email' => 'kovacek.cleo@example.net',
                'password_hash' => '$2y$12$MyMdefmMyn8YL2USYQPLn..A8LxXxk60cxxLs3mLB6X5KhPiA7OKW',
                'status' => 'active',
                'language' => 'rus',
                'theme' => 'system',
                'avatar_type' => 'preset',
                'avatar_preset' => null,
                'avatar_path' => null,
                'forgejo_user_id' => null,
                'forgejo_username' => null,
                'forgejo_access_token' => null,
                'forgejo_refresh_token' => null,
                'forgejo_token_expires_at' => null,
                'forgejo_connected_at' => null,
                'last_seen' => null,
                'created_at' => '2026-04-23 04:39:18',
                'updated_at' => '2026-04-23 04:39:18',
            ],
            [
                'user_id' => 5,
                'name' => 'xolodolov06@gmail.com',
                'email' => 'xolodolov06@gmail.com',
                'password_hash' => '$2y$12$UktBXQzeu/eJzIP.sbViLe0adUWONfXEfS8x8riA8XpQT8fVKi9V.',
                'status' => 'active',
                'language' => 'eng',
                'theme' => 'system',
                'avatar_type' => 'upload',
                'avatar_preset' => null,
                'avatar_path' => 'avatars/5/avatar-1781506616-pU0DF9bjzi2F.png',
                'forgejo_user_id' => null,
                'forgejo_username' => null,
                'forgejo_access_token' => null,
                'forgejo_refresh_token' => null,
                'forgejo_token_expires_at' => null,
                'forgejo_connected_at' => null,
                'last_seen' => null,
                'created_at' => '2026-06-14 09:35:05',
                'updated_at' => '2026-06-15 13:57:12',
            ],
            [
                'user_id' => 6,
                'name' => 'artur@mail.ru',
                'email' => 'artur@mail.ru',
                'password_hash' => '',
                'status' => 'active',
                'language' => 'rus',
                'theme' => 'system',
                'avatar_type' => 'preset',
                'avatar_preset' => null,
                'avatar_path' => null,
                'forgejo_user_id' => null,
                'forgejo_username' => null,
                'forgejo_access_token' => null,
                'forgejo_refresh_token' => null,
                'forgejo_token_expires_at' => null,
                'forgejo_connected_at' => null,
                'last_seen' => null,
                'created_at' => '2026-06-15 09:48:58',
                'updated_at' => '2026-06-15 09:48:58',
            ],
            [
                'user_id' => 7,
                'name' => 'andrei@mail.ru',
                'email' => 'andrei@mail.ru',
                'password_hash' => '',
                'status' => 'active',
                'language' => 'rus',
                'theme' => 'system',
                'avatar_type' => 'preset',
                'avatar_preset' => null,
                'avatar_path' => null,
                'forgejo_user_id' => null,
                'forgejo_username' => null,
                'forgejo_access_token' => null,
                'forgejo_refresh_token' => null,
                'forgejo_token_expires_at' => null,
                'forgejo_connected_at' => null,
                'last_seen' => null,
                'created_at' => '2026-06-15 09:49:02',
                'updated_at' => '2026-06-15 09:49:02',
            ],
        ];

        DB::table('users')->insert($users);
    }

    private function seedAdmin(): void
    {
        DB::table('admins')->insert([
            'admin_id' => 1,
            'user_id' => 1,
            'created_at' => now(),
        ]);
    }

    private function seedProjects(): void
    {
        $projects = [
            [
                'project_id' => 1,
                'name' => 'ву',
                'description' => 'у',
                'owner_id' => 1,
                'project_path' => 'projects/1_xolodilov06@mail.ru/ву',
                'is_public' => false,
                'git_enabled' => false,
                'forgejo_repo_id' => null,
                'forgejo_repo_full_name' => null,
                'forgejo_repo_clone_url' => null,
                'forgejo_repo_html_url' => null,
                'forgejo_default_branch' => null,
                'forgejo_connected_at' => null,
                'forgejo_last_push_at' => null,
                'created_at' => '2026-04-13 16:39:28',
                'updated_at' => '2026-04-13 16:39:28',
            ],
            [
                'project_id' => 2,
                'name' => 'dffdf',
                'description' => null,
                'owner_id' => 1,
                'project_path' => 'projects/1_xolodilov06@mail.ru/dffdf',
                'is_public' => false,
                'git_enabled' => false,
                'forgejo_repo_id' => null,
                'forgejo_repo_full_name' => null,
                'forgejo_repo_clone_url' => null,
                'forgejo_repo_html_url' => null,
                'forgejo_default_branch' => null,
                'forgejo_connected_at' => null,
                'forgejo_last_push_at' => null,
                'created_at' => '2026-04-17 02:03:33',
                'updated_at' => '2026-04-17 02:03:33',
            ],
            [
                'project_id' => 3,
                'name' => 'sit ab doloribus',
                'description' => 'Asperiores laboriosam iusto deserunt cupiditate consequuntur iusto.',
                'owner_id' => 3,
                'project_path' => 'facilis-aliquam-esse/nesciunt-et',
                'is_public' => false,
                'git_enabled' => false,
                'forgejo_repo_id' => null,
                'forgejo_repo_full_name' => null,
                'forgejo_repo_clone_url' => null,
                'forgejo_repo_html_url' => null,
                'forgejo_default_branch' => null,
                'forgejo_connected_at' => null,
                'forgejo_last_push_at' => null,
                'created_at' => '2026-04-23 04:39:18',
                'updated_at' => '2026-04-23 04:39:18',
            ],
            [
                'project_id' => 4,
                'name' => 'Тестовый проект 1',
                'description' => 'Описание тестового проекта 1',
                'owner_id' => 1,
                'project_path' => 'projects/1_xolodilov06@mail.ru/Тестовый проект 1',
                'is_public' => false,
                'git_enabled' => true,
                'forgejo_repo_id' => 17,
                'forgejo_repo_full_name' => 'chingazin/1',
                'forgejo_repo_clone_url' => 'http://localhost:3000/chingazin/1.git',
                'forgejo_repo_html_url' => 'http://localhost:3000/chingazin/1',
                'forgejo_default_branch' => 'main',
                'forgejo_connected_at' => '2026-06-10 04:40:35',
                'forgejo_last_push_at' => '2026-06-10 05:15:39',
                'created_at' => '2026-06-08 09:00:38',
                'updated_at' => '2026-06-10 12:15:39',
            ],
            [
                'project_id' => 5,
                'name' => 'df',
                'description' => null,
                'owner_id' => 1,
                'project_path' => 'projects/1_xolodilov06@mail.ru/df',
                'is_public' => false,
                'git_enabled' => true,
                'forgejo_repo_id' => 18,
                'forgejo_repo_full_name' => 'chingazin/ddfg',
                'forgejo_repo_clone_url' => 'http://localhost:3000/chingazin/ddfg.git',
                'forgejo_repo_html_url' => 'http://localhost:3000/chingazin/ddfg',
                'forgejo_default_branch' => 'main',
                'forgejo_connected_at' => '2026-06-14 09:04:14',
                'forgejo_last_push_at' => null,
                'created_at' => '2026-06-14 09:03:50',
                'updated_at' => '2026-06-14 16:04:15',
            ],
            [
                'project_id' => 6,
                'name' => 'task-cli',
                'description' => 'Task management CLI tool - simple task tracker with tags, priorities, and JSON export',
                'owner_id' => 1,
                'project_path' => 'projects/1_xolodilov06@mail.ru/task-cli',
                'is_public' => false,
                'git_enabled' => true,
                'forgejo_repo_id' => 19,
                'forgejo_repo_full_name' => 'chingazin/python-cli',
                'forgejo_repo_clone_url' => 'http://localhost:3000/chingazin/python-cli.git',
                'forgejo_repo_html_url' => 'http://localhost:3000/chingazin/python-cli',
                'forgejo_default_branch' => 'main',
                'forgejo_connected_at' => '2026-06-15 07:28:18',
                'forgejo_last_push_at' => '2026-06-15 06:46:08',
                'created_at' => '2026-06-15 09:48:41',
                'updated_at' => '2026-06-15 14:28:19',
            ],
            [
                'project_id' => 7,
                'name' => 'EcoTrack',
                'description' => 'Мобильное приложение для отслеживания углеродного следа и экологичных привычек пользователей с геймификацией и социальными челленджами.',
                'owner_id' => 1,
                'project_path' => 'projects/1_xolodilov06@mail.ru/EcoTrack',
                'is_public' => false,
                'git_enabled' => false,
                'forgejo_repo_id' => null,
                'forgejo_repo_full_name' => null,
                'forgejo_repo_clone_url' => null,
                'forgejo_repo_html_url' => null,
                'forgejo_default_branch' => null,
                'forgejo_connected_at' => null,
                'forgejo_last_push_at' => null,
                'created_at' => '2026-06-15 08:06:54',
                'updated_at' => '2026-06-15 08:06:54',
            ],
            [
                'project_id' => 8,
                'name' => 'PyDataViz',
                'description' => 'Интерактивная библиотека визуализации данных с автоматическим подбором типов графиков на основе структуры датасета и интеграцией с Jupyter Notebook.',
                'owner_id' => 1,
                'project_path' => 'projects/1_xolodilov06@mail.ru/PyDataViz',
                'is_public' => false,
                'git_enabled' => false,
                'forgejo_repo_id' => null,
                'forgejo_repo_full_name' => null,
                'forgejo_repo_clone_url' => null,
                'forgejo_repo_html_url' => null,
                'forgejo_default_branch' => null,
                'forgejo_connected_at' => null,
                'forgejo_last_push_at' => null,
                'created_at' => '2026-06-15 08:07:25',
                'updated_at' => '2026-06-15 08:07:25',
            ],
            [
                'project_id' => 9,
                'name' => 'ReactFlow',
                'description' => 'Конструктор бизнес-процессов с drag-and-drop интерфейсом, позволяющий создавать workflow диаграммы с автоматической генерацией',
                'owner_id' => 1,
                'project_path' => 'projects/1_xolodilov06@mail.ru/ReactFlow',
                'is_public' => false,
                'git_enabled' => false,
                'forgejo_repo_id' => null,
                'forgejo_repo_full_name' => null,
                'forgejo_repo_clone_url' => null,
                'forgejo_repo_html_url' => null,
                'forgejo_default_branch' => null,
                'forgejo_connected_at' => null,
                'forgejo_last_push_at' => null,
                'created_at' => '2026-06-15 08:07:45',
                'updated_at' => '2026-06-15 08:07:45',
            ],
            [
                'project_id' => 10,
                'name' => 'KotlinChat',
                'description' => 'Кроссплатформенное мобильное приложение для обмена сообщениями с end-to-end шифрованием, работающее на Android и iOS через Kotlin Multiplatform.',
                'owner_id' => 1,
                'project_path' => 'projects/1_xolodilov06@mail.ru/KotlinChat',
                'is_public' => false,
                'git_enabled' => false,
                'forgejo_repo_id' => null,
                'forgejo_repo_full_name' => null,
                'forgejo_repo_clone_url' => null,
                'forgejo_repo_html_url' => null,
                'forgejo_default_branch' => null,
                'forgejo_connected_at' => null,
                'forgejo_last_push_at' => null,
                'created_at' => '2026-06-15 08:08:10',
                'updated_at' => '2026-06-15 08:08:10',
            ],
            [
                'project_id' => 11,
                'name' => 'PHPBlog',
                'description' => 'CMS для блогеров с SEO-оптимизацией, системой комментариев и встроенным редактором контента.',
                'owner_id' => 1,
                'project_path' => 'projects/1_xolodilov06@mail.ru/PHPBlog',
                'is_public' => false,
                'git_enabled' => false,
                'forgejo_repo_id' => null,
                'forgejo_repo_full_name' => null,
                'forgejo_repo_clone_url' => null,
                'forgejo_repo_html_url' => null,
                'forgejo_default_branch' => null,
                'forgejo_connected_at' => null,
                'forgejo_last_push_at' => null,
                'created_at' => '2026-06-15 08:08:32',
                'updated_at' => '2026-06-15 08:08:32',
            ],
        ];

        DB::table('projects')->insert($projects);
    }

    private function seedParticipants(): void
    {
        $participants = [
            ['participant_id' => 1, 'project_id' => 1, 'user_id' => 2, 'role' => 'developer', 'joined_at' => '2026-04-14 07:51:35'],
            ['participant_id' => 2, 'project_id' => 2, 'user_id' => 2, 'role' => 'developer', 'joined_at' => '2026-04-22 14:08:43'],
            ['participant_id' => 3, 'project_id' => 3, 'user_id' => 4, 'role' => 'viewer', 'joined_at' => '2026-04-23 04:39:18'],
            ['participant_id' => 4, 'project_id' => 4, 'user_id' => 2, 'role' => 'viewer', 'joined_at' => '2026-06-08 09:15:22'],
            ['participant_id' => 5, 'project_id' => 4, 'user_id' => 4, 'role' => 'developer', 'joined_at' => '2026-06-08 09:15:27'],
            ['participant_id' => 6, 'project_id' => 4, 'user_id' => 3, 'role' => 'maintainer', 'joined_at' => '2026-06-08 09:15:39'],
            ['participant_id' => 7, 'project_id' => 4, 'user_id' => 5, 'role' => 'developer', 'joined_at' => '2026-06-14 09:35:45'],
            ['participant_id' => 8, 'project_id' => 6, 'user_id' => 6, 'role' => 'developer', 'joined_at' => '2026-04-26 10:00:00'],
            ['participant_id' => 9, 'project_id' => 6, 'user_id' => 7, 'role' => 'developer', 'joined_at' => '2026-05-09 11:00:00'],
            ['participant_id' => 11, 'project_id' => 6, 'user_id' => 5, 'role' => 'developer', 'joined_at' => '2026-06-15 08:45:13'],
        ];

        DB::table('project_participants')->insert($participants);
    }

    private function seedInvitations(): void
    {
        DB::table('project_invitations')->insert([
            'invitation_id' => 2,
            'project_id' => 6,
            'inviter_user_id' => 1,
            'invite_token' => 'fImFurabafzws15DongDRsg8dNnMp2FD6Y1HUc2BXa5yGK57aBYnHEz6A8DaIBKZ',
            'expires_at' => null,
            'created_at' => '2026-06-15 14:18:16',
        ]);
    }

    private function seedNotifications(): void
    {
        $notifications = [
            [
                'notification_id' => 1,
                'user_id' => 1,
                'type' => 'task_completed',
                'title' => 'Task Completed',
                'message' => 'Task "увув" has been completed',
                'data' => '{"project_id":1,"project_task_id":1}',
                'is_read' => true,
                'read_at' => '2026-04-25 07:54:41',
                'created_at' => '2026-04-13 16:40:30',
                'updated_at' => '2026-04-25 07:54:41',
            ],
            [
                'notification_id' => 2,
                'user_id' => 1,
                'type' => 'task_completed',
                'title' => 'Task Completed',
                'message' => 'Task "вва" has been completed',
                'data' => '{"project_id":1,"project_task_id":2}',
                'is_read' => true,
                'read_at' => '2026-04-25 07:54:41',
                'created_at' => '2026-04-14 07:45:19',
                'updated_at' => '2026-04-25 07:54:41',
            ],
            [
                'notification_id' => 3,
                'user_id' => 1,
                'type' => 'task_reopened',
                'title' => 'Task Reopened',
                'message' => 'Task "вва" has been reopened',
                'data' => '{"project_id":1,"project_task_id":2}',
                'is_read' => true,
                'read_at' => '2026-04-25 07:54:41',
                'created_at' => '2026-04-14 07:45:21',
                'updated_at' => '2026-04-25 07:54:41',
            ],
            [
                'notification_id' => 4,
                'user_id' => 1,
                'type' => 'task_completed',
                'title' => 'Task Completed',
                'message' => 'Task "f" has been completed',
                'data' => '{"project_id":2,"project_task_id":6}',
                'is_read' => true,
                'read_at' => '2026-04-25 07:54:41',
                'created_at' => '2026-04-25 07:40:44',
                'updated_at' => '2026-04-25 07:54:41',
            ],
            [
                'notification_id' => 5,
                'user_id' => 1,
                'type' => 'task_completed',
                'title' => 'Task Completed',
                'message' => 'Task "f" has been completed',
                'data' => '{"project_id":2,"project_task_id":6}',
                'is_read' => true,
                'read_at' => '2026-04-25 07:54:41',
                'created_at' => '2026-04-25 07:40:48',
                'updated_at' => '2026-04-25 07:54:41',
            ],
        ];

        DB::table('notifications')->insert($notifications);
    }

    private function seedCodeComments(): void
    {
        DB::table('project_code_comments')->insert([
            'comment_id' => 1,
            'project_id' => 2,
            'author_user_id' => 1,
            'path' => 'efefe.py',
            'line_number' => 1,
            'body' => 'ывыв',
            'created_at' => '2026-04-17 02:06:50',
        ]);
    }

    private function seedTasks(): void
    {
        $tasks = [
            [
                'project_task_id' => 2,
                'project_id' => 1,
                'created_by_user_id' => 1,
                'assigned_to_user_id' => 1,
                'title' => 'вва',
                'description' => 'уауа',
                'status' => 'backlog',
                'priority' => 3,
                'due_date' => '2026-04-22',
                'assigned_at' => '2026-04-14 07:45:18',
                'started_at' => '2026-04-14 07:45:18',
                'completed_at' => null,
                'created_at' => '2026-04-14 07:19:15',
                'updated_at' => '2026-04-14 07:47:13',
            ],
            [
                'project_task_id' => 3,
                'project_id' => 1,
                'created_by_user_id' => 1,
                'assigned_to_user_id' => null,
                'title' => 'ууа',
                'description' => 'аа4а4а',
                'status' => 'backlog',
                'priority' => 0,
                'due_date' => '2026-04-18',
                'assigned_at' => null,
                'started_at' => null,
                'completed_at' => null,
                'created_at' => '2026-04-14 07:48:45',
                'updated_at' => '2026-04-14 07:48:45',
            ],
            [
                'project_task_id' => 4,
                'project_id' => 2,
                'created_by_user_id' => 1,
                'assigned_to_user_id' => 2,
                'title' => 'цц',
                'description' => 'цц',
                'status' => 'in_progress',
                'priority' => 1,
                'due_date' => null,
                'assigned_at' => '2026-04-22 14:10:25',
                'started_at' => '2026-04-22 14:10:25',
                'completed_at' => null,
                'created_at' => '2026-04-22 14:10:02',
                'updated_at' => '2026-04-22 14:10:25',
            ],
            [
                'project_task_id' => 5,
                'project_id' => 2,
                'created_by_user_id' => 1,
                'assigned_to_user_id' => 2,
                'title' => 'Сделать парсер озона',
                'description' => 'ваав',
                'status' => 'in_progress',
                'priority' => 1,
                'due_date' => '3223-02-12',
                'assigned_at' => '2026-04-25 07:40:03',
                'started_at' => '2026-04-25 07:40:03',
                'completed_at' => null,
                'created_at' => '2026-04-25 07:39:22',
                'updated_at' => '2026-04-25 07:40:03',
            ],
            [
                'project_task_id' => 6,
                'project_id' => 2,
                'created_by_user_id' => 1,
                'assigned_to_user_id' => 1,
                'title' => 'f',
                'description' => 'efe',
                'status' => 'done',
                'priority' => 1,
                'due_date' => '1212-12-12',
                'assigned_at' => '2026-04-25 07:40:42',
                'started_at' => '2026-04-25 07:40:42',
                'completed_at' => '2026-04-25 07:40:48',
                'created_at' => '2026-04-25 07:40:38',
                'updated_at' => '2026-04-25 07:40:48',
            ],
            [
                'project_task_id' => 7,
                'project_id' => 4,
                'created_by_user_id' => 1,
                'assigned_to_user_id' => 1,
                'title' => 'Создать папку utils',
                'description' => 'Добавить в неё парсер сайта авито, валидатор запросов и поисковик по категориям',
                'status' => 'in_progress',
                'priority' => 1,
                'due_date' => '2026-06-21',
                'assigned_at' => '2026-06-10 05:07:22',
                'started_at' => '2026-06-10 05:07:22',
                'completed_at' => null,
                'created_at' => '2026-06-10 05:05:09',
                'updated_at' => '2026-06-10 05:07:22',
            ],
            [
                'project_task_id' => 8,
                'project_id' => 4,
                'created_by_user_id' => 1,
                'assigned_to_user_id' => 1,
                'title' => 'Сверстать страницу товаров',
                'description' => 'По предоставленным мок-данным сделать верстку страницы товаров',
                'status' => 'backlog',
                'priority' => 1,
                'due_date' => null,
                'assigned_at' => '2026-06-10 05:06:08',
                'started_at' => '2026-06-10 05:06:08',
                'completed_at' => null,
                'created_at' => '2026-06-10 05:06:06',
                'updated_at' => '2026-06-10 05:07:21',
            ],
            [
                'project_task_id' => 9,
                'project_id' => 4,
                'created_by_user_id' => 1,
                'assigned_to_user_id' => null,
                'title' => 'Разработать базу данных системы 3НФ',
                'description' => 'Включить в неё таблицы пользователей, администраторов, товаров, новостей',
                'status' => 'done',
                'priority' => 2,
                'due_date' => '2026-06-13',
                'assigned_at' => null,
                'started_at' => null,
                'completed_at' => '2026-06-10 05:07:18',
                'created_at' => '2026-06-10 05:07:15',
                'updated_at' => '2026-06-10 05:07:18',
            ],
        ];

        DB::table('project_tasks')->insert($tasks);
    }

    private function seedTerminalSessions(): void
    {
        $sessions = [
            [
                'terminal_session_id' => 1,
                'project_id' => 1,
                'user_id' => 1,
                'name' => 'Терминал 1',
                'shell' => 'powershell.exe',
                'cwd' => '/',
                'shared' => false,
                'status' => 'closed',
                'meta' => '{"created_by":1}',
                'last_activity_at' => '2026-06-08 07:11:27',
                'closed_at' => '2026-06-08 07:11:27',
                'created_at' => '2026-04-17 02:01:06',
                'updated_at' => '2026-06-08 07:11:27',
            ],
            [
                'terminal_session_id' => 2,
                'project_id' => 2,
                'user_id' => 1,
                'name' => 'Терминал 1',
                'shell' => 'powershell.exe',
                'cwd' => '/',
                'shared' => false,
                'status' => 'closed',
                'meta' => '{"created_by":1,"gateway_last_close":{"reason":"process-exit","runtime":"docker","exit_code":137,"signal":null,"closed_at":"2026-04-22T13:44:14.237000Z"},"gateway_close_history":[{"reason":"process-exit","runtime":"docker","exit_code":137,"signal":null,"closed_at":"2026-04-22T13:44:14.237000Z"}]}',
                'last_activity_at' => '2026-04-22 13:44:14',
                'closed_at' => '2026-04-22 13:44:14',
                'created_at' => '2026-04-17 02:06:55',
                'updated_at' => '2026-04-22 13:44:14',
            ],
            [
                'terminal_session_id' => 3,
                'project_id' => 2,
                'user_id' => 1,
                'name' => 'Терминал 2',
                'shell' => 'powershell.exe',
                'cwd' => '/',
                'shared' => false,
                'status' => 'closed',
                'meta' => '{"created_by":1,"gateway_last_close":{"reason":"process-exit","runtime":"docker","exit_code":137,"signal":null,"closed_at":"2026-04-22T13:44:13.771000Z"},"gateway_close_history":[{"reason":"process-exit","runtime":"docker","exit_code":137,"signal":null,"closed_at":"2026-04-22T13:44:13.771000Z"}]}',
                'last_activity_at' => '2026-04-22 13:44:13',
                'closed_at' => '2026-04-22 13:44:13',
                'created_at' => '2026-04-17 02:08:13',
                'updated_at' => '2026-04-22 13:44:14',
            ],
            [
                'terminal_session_id' => 4,
                'project_id' => 2,
                'user_id' => 2,
                'name' => 'Терминал 1',
                'shell' => 'powershell.exe',
                'cwd' => '/',
                'shared' => false,
                'status' => 'closed',
                'meta' => '{"created_by":2,"gateway_last_close":{"reason":"process-exit","runtime":"docker","exit_code":137,"signal":null,"closed_at":"2026-04-22T14:14:56.617000Z"},"gateway_close_history":[{"reason":"process-exit","runtime":"docker","exit_code":137,"signal":null,"closed_at":"2026-04-22T14:14:56.617000Z"}]}',
                'last_activity_at' => '2026-04-22 14:14:56',
                'closed_at' => '2026-04-22 14:14:56',
                'created_at' => '2026-04-22 14:14:38',
                'updated_at' => '2026-04-22 14:14:56',
            ],
            [
                'terminal_session_id' => 5,
                'project_id' => 2,
                'user_id' => 1,
                'name' => 'Терминал 4',
                'shell' => 'powershell.exe',
                'cwd' => '/',
                'shared' => false,
                'status' => 'closed',
                'meta' => '{"created_by":1,"gateway_last_close":{"reason":"process-exit","runtime":"docker","exit_code":137,"signal":null,"closed_at":"2026-04-25T07:59:55.695000Z"},"gateway_close_history":[{"reason":"process-exit","runtime":"docker","exit_code":137,"signal":null,"closed_at":"2026-04-25T07:59:55.695000Z"}]}',
                'last_activity_at' => '2026-04-25 07:59:55',
                'closed_at' => '2026-04-25 07:59:48',
                'created_at' => '2026-04-25 07:45:13',
                'updated_at' => '2026-04-25 07:59:57',
            ],
            [
                'terminal_session_id' => 6,
                'project_id' => 1,
                'user_id' => 1,
                'name' => 'Терминал 2',
                'shell' => 'powershell.exe',
                'cwd' => '/',
                'shared' => false,
                'status' => 'closed',
                'meta' => '{"created_by":1}',
                'last_activity_at' => '2026-06-08 07:11:29',
                'closed_at' => '2026-06-08 07:11:29',
                'created_at' => '2026-06-08 07:04:05',
                'updated_at' => '2026-06-08 07:11:29',
            ],
            [
                'terminal_session_id' => 7,
                'project_id' => 1,
                'user_id' => 1,
                'name' => 'Терминал 3',
                'shell' => 'powershell.exe',
                'cwd' => '/',
                'shared' => false,
                'status' => 'closed',
                'meta' => '{"created_by":1}',
                'last_activity_at' => '2026-06-08 07:15:06',
                'closed_at' => '2026-06-08 07:15:06',
                'created_at' => '2026-06-08 07:11:37',
                'updated_at' => '2026-06-08 07:15:06',
            ],
            [
                'terminal_session_id' => 8,
                'project_id' => 1,
                'user_id' => 1,
                'name' => 'Терминал 4',
                'shell' => 'powershell.exe',
                'cwd' => '/',
                'shared' => false,
                'status' => 'closed',
                'meta' => '{"created_by":1}',
                'last_activity_at' => '2026-06-08 07:19:17',
                'closed_at' => '2026-06-08 07:19:17',
                'created_at' => '2026-06-08 07:15:36',
                'updated_at' => '2026-06-08 07:19:17',
            ],
            [
                'terminal_session_id' => 9,
                'project_id' => 1,
                'user_id' => 1,
                'name' => 'Терминал 5',
                'shell' => 'powershell.exe',
                'cwd' => '/',
                'shared' => false,
                'status' => 'closed',
                'meta' => '{"created_by":1}',
                'last_activity_at' => '2026-06-08 07:23:54',
                'closed_at' => '2026-06-08 07:23:54',
                'created_at' => '2026-06-08 07:19:31',
                'updated_at' => '2026-06-08 07:23:54',
            ],
            [
                'terminal_session_id' => 10,
                'project_id' => 1,
                'user_id' => 1,
                'name' => 'Терминал 6',
                'shell' => 'powershell.exe',
                'cwd' => '/',
                'shared' => false,
                'status' => 'closed',
                'meta' => '{"created_by":1}',
                'last_activity_at' => '2026-06-08 07:25:46',
                'closed_at' => '2026-06-08 07:25:46',
                'created_at' => '2026-06-08 07:23:57',
                'updated_at' => '2026-06-08 07:25:46',
            ],
            [
                'terminal_session_id' => 11,
                'project_id' => 1,
                'user_id' => 1,
                'name' => 'Терминал 7',
                'shell' => 'powershell.exe',
                'cwd' => '/',
                'shared' => false,
                'status' => 'closed',
                'meta' => '{"created_by":1}',
                'last_activity_at' => '2026-06-08 07:27:53',
                'closed_at' => '2026-06-08 07:27:53',
                'created_at' => '2026-06-08 07:25:51',
                'updated_at' => '2026-06-08 07:25:51',
            ],
            [
                'terminal_session_id' => 12,
                'project_id' => 1,
                'user_id' => 1,
                'name' => 'Терминал 8',
                'shell' => 'powershell.exe',
                'cwd' => '/',
                'shared' => false,
                'status' => 'closed',
                'meta' => '{"created_by":1,"gateway_last_close":{"reason":"idle-timeout","runtime":"docker","exit_code":null,"signal":null,"closed_at":"2026-06-08T07:53:30.283000Z"},"gateway_close_history":[{"reason":"idle-timeout","runtime":"docker","exit_code":null,"signal":null,"closed_at":"2026-06-08T07:53:30.283000Z"}]}',
                'last_activity_at' => '2026-06-08 07:53:30',
                'closed_at' => '2026-06-08 07:38:25',
                'created_at' => '2026-06-08 07:27:55',
                'updated_at' => '2026-06-08 07:53:30',
            ],
            [
                'terminal_session_id' => 13,
                'project_id' => 1,
                'user_id' => 1,
                'name' => 'Терминал 9',
                'shell' => 'powershell.exe',
                'cwd' => '/',
                'shared' => false,
                'status' => 'closed',
                'meta' => '{"created_by":1,"gateway_last_close":{"reason":"idle-timeout","runtime":"docker","exit_code":null,"signal":null,"closed_at":"2026-06-08T07:58:35.736000Z"},"gateway_close_history":[{"reason":"idle-timeout","runtime":"docker","exit_code":null,"signal":null,"closed_at":"2026-06-08T07:58:35.736000Z"}]}',
                'last_activity_at' => '2026-06-08 07:58:35',
                'closed_at' => '2026-06-08 07:58:35',
                'created_at' => '2026-06-08 07:38:29',
                'updated_at' => '2026-06-08 07:58:35',
            ],
            [
                'terminal_session_id' => 14,
                'project_id' => 4,
                'user_id' => 1,
                'name' => 'Терминал 1',
                'shell' => 'powershell.exe',
                'cwd' => '/',
                'shared' => false,
                'status' => 'closed',
                'meta' => '{"created_by":1,"gateway_last_close":{"reason":"idle-timeout","runtime":"docker","exit_code":null,"signal":null,"closed_at":"2026-06-10T05:27:01.057000Z"},"gateway_close_history":[{"reason":"idle-timeout","runtime":"docker","exit_code":null,"signal":null,"closed_at":"2026-06-10T05:27:01.057000Z"}]}',
                'last_activity_at' => '2026-06-10 05:27:01',
                'closed_at' => '2026-06-10 05:27:01',
                'created_at' => '2026-06-10 05:11:18',
                'updated_at' => '2026-06-10 05:27:01',
            ],
            [
                'terminal_session_id' => 15,
                'project_id' => 5,
                'user_id' => 1,
                'name' => 'Терминал 1',
                'shell' => 'powershell.exe',
                'cwd' => '/',
                'shared' => false,
                'status' => 'closed',
                'meta' => '{"created_by":1,"gateway_last_close":{"reason":"idle-timeout","runtime":"docker","exit_code":null,"signal":null,"closed_at":"2026-06-14T09:28:28.779000Z"},"gateway_close_history":[{"reason":"idle-timeout","runtime":"docker","exit_code":null,"signal":null,"closed_at":"2026-06-14T09:28:28.779000Z"}]}',
                'last_activity_at' => '2026-06-14 09:28:28',
                'closed_at' => '2026-06-14 09:28:28',
                'created_at' => '2026-06-14 09:04:26',
                'updated_at' => '2026-06-14 09:28:29',
            ],
            [
                'terminal_session_id' => 16,
                'project_id' => 4,
                'user_id' => 1,
                'name' => 'Терминал 2',
                'shell' => 'powershell.exe',
                'cwd' => '/',
                'shared' => false,
                'status' => 'closed',
                'meta' => '{"created_by":1,"gateway_last_close":{"reason":"idle-timeout","runtime":"docker","exit_code":null,"signal":null,"closed_at":"2026-06-15T07:08:28.198000Z"},"gateway_close_history":[{"reason":"idle-timeout","runtime":"docker","exit_code":null,"signal":null,"closed_at":"2026-06-15T07:08:28.198000Z"}]}',
                'last_activity_at' => '2026-06-15 07:08:28',
                'closed_at' => '2026-06-15 07:08:28',
                'created_at' => '2026-06-15 06:53:17',
                'updated_at' => '2026-06-15 07:08:28',
            ],
            [
                'terminal_session_id' => 17,
                'project_id' => 6,
                'user_id' => 1,
                'name' => 'Терминал 1',
                'shell' => 'powershell.exe',
                'cwd' => '/',
                'shared' => false,
                'status' => 'closed',
                'meta' => '{"created_by":1,"gateway_last_close":{"reason":"idle-timeout","runtime":"docker","exit_code":null,"signal":null,"closed_at":"2026-06-15T08:15:43.235000Z"},"gateway_close_history":[{"reason":"idle-timeout","runtime":"docker","exit_code":null,"signal":null,"closed_at":"2026-06-15T08:15:43.235000Z"}]}',
                'last_activity_at' => '2026-06-15 08:15:43',
                'closed_at' => '2026-06-15 08:15:43',
                'created_at' => '2026-06-15 07:15:39',
                'updated_at' => '2026-06-15 08:15:43',
            ],
        ];

        DB::table('project_terminal_sessions')->insert($sessions);
    }

    private function resetSequences(): void
    {
        $sequences = [
            'users_user_id_seq' => 'users',
            'projects_project_id_seq' => 'projects',
            'project_participants_participant_id_seq' => 'project_participants',
            'project_invitations_invitation_id_seq' => 'project_invitations',
            'project_code_comments_comment_id_seq' => 'project_code_comments',
            'project_tasks_project_task_id_seq' => 'project_tasks',
            'project_terminal_sessions_terminal_session_id_seq' => 'project_terminal_sessions',
            'notifications_notification_id_seq' => 'notifications',
            'registration_verifications_registration_verification_id_seq' => 'registration_verifications',
            'admins_admin_id_seq' => 'admins',
            'personal_access_tokens_id_seq' => 'personal_access_tokens',
        ];

        foreach ($sequences as $sequence => $table) {
            $max = DB::table($table)->max(DB::raw('COALESCE(' . $this->getPkColumn($table) . ', 0)'));
            if ($max) {
                DB::statement("ALTER SEQUENCE {$sequence} RESTART WITH " . ((int) $max + 1));
            }
        }
    }

    private function getPkColumn(string $table): string
    {
        return match ($table) {
            'users' => 'user_id',
            'projects' => 'project_id',
            'project_participants' => 'participant_id',
            'project_invitations' => 'invitation_id',
            'project_code_comments' => 'comment_id',
            'project_tasks' => 'project_task_id',
            'project_terminal_sessions' => 'terminal_session_id',
            'notifications' => 'notification_id',
            'registration_verifications' => 'registration_verification_id',
            'admins' => 'admin_id',
            'personal_access_tokens' => 'id',
            default => 'id',
        };
    }
}
