function createResourceEndpoints({
  resource,
  group,
  idParam = "id",
  createBody = {},
  updateBody = {},
  sampleListQuery = { per_page: 20 },
  adminOnly = false,
}) {
  const basePath = `/${resource}`;
  const itemUri = `${basePath}/{${idParam}}`;
  const itemPath = `${basePath}/1`;
  const authText = adminOnly
    ? "Requires auth:sanctum and admin middleware."
    : "Requires auth:sanctum.";

  return [
    {
      id: `${resource}-index`,
      group,
      title: `List ${resource}`,
      method: "GET",
      uri: basePath,
      path: basePath,
      auth: true,
      adminOnly,
      description: `Paginated list endpoint. ${authText}`,
      sampleQuery: sampleListQuery,
    },
    {
      id: `${resource}-store`,
      group,
      title: `Create ${resource}`,
      method: "POST",
      uri: basePath,
      path: basePath,
      auth: true,
      adminOnly,
      description: `Create resource item. ${authText}`,
      sampleBody: createBody,
    },
    {
      id: `${resource}-show`,
      group,
      title: `Get ${resource} item`,
      method: "GET",
      uri: itemUri,
      path: itemPath,
      auth: true,
      adminOnly,
      description: `Read one item by id. ${authText}`,
    },
    {
      id: `${resource}-update-put`,
      group,
      title: `Update ${resource} item (PUT)`,
      method: "PUT",
      uri: itemUri,
      path: itemPath,
      auth: true,
      adminOnly,
      description: `Full update by id. ${authText}`,
      sampleBody: updateBody,
    },
    {
      id: `${resource}-update-patch`,
      group,
      title: `Update ${resource} item (PATCH)`,
      method: "PATCH",
      uri: itemUri,
      path: itemPath,
      auth: true,
      adminOnly,
      description: `Partial update by id. ${authText}`,
      sampleBody: updateBody,
    },
    {
      id: `${resource}-destroy`,
      group,
      title: `Delete ${resource} item`,
      method: "DELETE",
      uri: itemUri,
      path: itemPath,
      auth: true,
      adminOnly,
      description: `Delete by id. ${authText}`,
    },
  ];
}

export const apiEndpoints = [
  {
    id: "auth-register",
    group: "Auth",
    title: "Register user",
    method: "POST",
    uri: "/auth/register",
    path: "/auth/register",
    auth: false,
    description: "Create user account and get Bearer token. Status is set to active server-side.",
    sampleBody: {
      name: "Demo User",
      email: "demo@example.com",
      password: "password123",
      language: "rus",
    },
  },
  {
    id: "auth-login",
    group: "Auth",
    title: "Login user",
    method: "POST",
    uri: "/auth/login",
    path: "/auth/login",
    auth: false,
    description: "Login with email/password and get Bearer token.",
    sampleBody: {
      email: "demo@example.com",
      password: "password123",
    },
  },
  {
    id: "forgejo-start",
    group: "Forgejo",
    title: "Start Forgejo OAuth",
    method: "POST",
    uri: "/forgejo/oauth/start",
    path: "/forgejo/oauth/start",
    auth: false,
    description: "Start OAuth flow. mode=login works public, mode=connect requires token.",
    sampleBody: {
      mode: "login",
    },
  },
  {
    id: "forgejo-callback",
    group: "Forgejo",
    title: "Forgejo OAuth callback",
    method: "GET",
    uri: "/forgejo/oauth/callback",
    path: "/forgejo/oauth/callback",
    auth: false,
    description: "Exchange OAuth code + state for app session/token.",
    sampleQuery: {
      code: "paste-code",
      state: "paste-state",
    },
  },
  {
    id: "session-me",
    group: "Session",
    title: "Current user (/me)",
    method: "GET",
    uri: "/me",
    path: "/me",
    auth: true,
    description: "Return current authenticated user.",
  },
  {
    id: "session-profile-update",
    group: "Session",
    title: "Update current profile",
    method: "PATCH",
    uri: "/me/profile",
    path: "/me/profile",
    auth: true,
    description: "Update name/language and selected profile preset.",
    sampleBody: {
      name: "Demo User",
      language: "eng",
      avatar_preset: "robot",
    },
  },
  {
    id: "session-avatar-upload",
    group: "Session",
    title: "Upload profile avatar",
    method: "POST",
    uri: "/me/avatar",
    path: "/me/avatar",
    auth: true,
    description: "Upload an avatar image via multipart/form-data.",
  },
  {
    id: "session-avatar-delete",
    group: "Session",
    title: "Delete uploaded avatar",
    method: "DELETE",
    uri: "/me/avatar",
    path: "/me/avatar",
    auth: true,
    description: "Remove uploaded avatar and switch back to preset icon.",
  },
  {
    id: "auth-logout",
    group: "Session",
    title: "Logout current token",
    method: "POST",
    uri: "/auth/logout",
    path: "/auth/logout",
    auth: true,
    description: "Invalidate current token.",
  },
  {
    id: "auth-logout-all",
    group: "Session",
    title: "Logout all tokens",
    method: "POST",
    uri: "/auth/logout-all",
    path: "/auth/logout-all",
    auth: true,
    description: "Invalidate all user tokens.",
  },
  ...createResourceEndpoints({
    resource: "users",
    group: "Users",
    idParam: "user",
    createBody: {
      name: "Another User",
      email: "another@example.com",
      password: "password123",
      status: "active",
      language: "rus",
    },
    updateBody: {
      name: "Updated User Name",
      status: "active",
      language: "eng",
    },
  }),
  ...createResourceEndpoints({
    resource: "projects",
    group: "Projects",
    idParam: "project",
    createBody: {
      name: "My project",
      description: "Project from SPA",
      is_public: false,
    },
    updateBody: {
      name: "My project renamed",
      description: "Updated description",
      is_public: true,
    },
  }),
  {
    id: "project-filesystem",
    group: "Projects",
    title: "Project filesystem action",
    method: "POST",
    uri: "/projects/{projectId}/filesystem",
    path: "/projects/1/filesystem",
    auth: true,
    description: "Create file or folder inside project path.",
    sampleBody: {
      action: "create_file",
      path: "README.md",
      content: "# Hello from frontend",
    },
  },
  {
    id: "project-filesystem-tree",
    group: "Projects",
    title: "Project filesystem tree",
    method: "GET",
    uri: "/projects/{projectId}/filesystem/tree",
    path: "/projects/1/filesystem/tree",
    auth: true,
    description: "Read full project file tree.",
  },
  {
    id: "project-filesystem-read-file",
    group: "Projects",
    title: "Read project file",
    method: "GET",
    uri: "/projects/{projectId}/filesystem/file?path=...",
    path: "/projects/1/filesystem/file",
    auth: true,
    description: "Read file content by relative path.",
    sampleQuery: {
      path: "README.md",
    },
  },
  {
    id: "project-filesystem-write-file",
    group: "Projects",
    title: "Write project file",
    method: "PUT",
    uri: "/projects/{projectId}/filesystem/file",
    path: "/projects/1/filesystem/file",
    auth: true,
    description: "Create or update file by relative path.",
    sampleBody: {
      path: "README.md",
      content: "# Updated file",
    },
  },
  {
    id: "project-filesystem-move-item",
    group: "Projects",
    title: "Move project file/folder",
    method: "PUT",
    uri: "/projects/{projectId}/filesystem/move",
    path: "/projects/1/filesystem/move",
    auth: true,
    description: "Move/rename file or folder inside project.",
    sampleBody: {
      from_path: "src/main.js",
      to_path: "src/app/main.js",
    },
  },
  {
    id: "project-filesystem-delete-item",
    group: "Projects",
    title: "Delete project file/folder",
    method: "DELETE",
    uri: "/projects/{projectId}/filesystem/item?path=...",
    path: "/projects/1/filesystem/item",
    auth: true,
    description: "Delete file or folder by relative path.",
    sampleQuery: {
      path: "README.md",
    },
  },
  {
    id: "project-forgejo-connect",
    group: "Projects",
    title: "Connect project to Forgejo",
    method: "POST",
    uri: "/projects/{projectId}/forgejo/connect",
    path: "/projects/1/forgejo/connect",
    auth: true,
    description: "Create a new Forgejo repository or connect an existing one by HTTPS/SSH repo_url.",
    sampleBody: {
      mode: "existing",
      repo_url: "https://forgejo.example.com/team/my-project.git",
    },
  },
  {
    id: "project-forgejo-save",
    group: "Projects",
    title: "Push project to Forgejo",
    method: "POST",
    uri: "/projects/{projectId}/forgejo/save",
    path: "/projects/1/forgejo/save",
    auth: true,
    description: "Commit all files and push to configured Forgejo repository.",
    sampleBody: {
      message: "Manual save from SPA",
    },
  },
  {
    id: "project-realtime-heartbeat",
    group: "Projects",
    title: "Realtime heartbeat",
    method: "POST",
    uri: "/projects/{projectId}/realtime/heartbeat",
    path: "/projects/1/realtime/heartbeat",
    auth: true,
    description: "Update presence and cursor position for current editor session.",
    sampleBody: {
      path: "src/main.js",
      cursor_row: 12,
      cursor_column: 4,
    },
  },
  {
    id: "project-realtime-presence",
    group: "Projects",
    title: "Realtime presence list",
    method: "GET",
    uri: "/projects/{projectId}/realtime/presence",
    path: "/projects/1/realtime/presence",
    auth: true,
    description: "Get currently online collaborators and their cursor positions.",
  },
  {
    id: "project-realtime-chat-list",
    group: "Projects",
    title: "Realtime chat messages",
    method: "GET",
    uri: "/projects/{projectId}/realtime/chat?after_id=...",
    path: "/projects/1/realtime/chat",
    auth: true,
    description: "Read session chat messages after selected message id.",
    sampleQuery: {
      after_id: 0,
      limit: 50,
    },
  },
  {
    id: "project-realtime-chat-send",
    group: "Projects",
    title: "Send realtime chat message",
    method: "POST",
    uri: "/projects/{projectId}/realtime/chat",
    path: "/projects/1/realtime/chat",
    auth: true,
    description: "Send chat message into active collaboration session.",
    sampleBody: {
      message: "Let's refactor this module.",
    },
  },
  {
    id: "project-realtime-editor-state",
    group: "Projects",
    title: "Realtime editor state",
    method: "POST",
    uri: "/projects/{projectId}/realtime/editor-state",
    path: "/projects/1/realtime/editor-state",
    auth: true,
    description: "Get or initialize collaborative editor state for a file path.",
    sampleBody: {
      path: "src/main.js",
      seed_content: "console.log('hello')",
    },
  },
  {
    id: "project-realtime-editor-sync",
    group: "Projects",
    title: "Realtime editor operation",
    method: "POST",
    uri: "/projects/{projectId}/realtime/editor-sync",
    path: "/projects/1/realtime/editor-sync",
    auth: true,
    description: "Submit incremental editor operation with optimistic revision.",
    sampleBody: {
      path: "src/main.js",
      client_id: "browser-tab-1",
      op_id: "op-0001",
      base_revision: 12,
      start: 18,
      delete_count: 0,
      insert_text: ";",
      cursor_row: 1,
      cursor_column: 5,
    },
  },
  ...createResourceEndpoints({
    resource: "project-participants",
    group: "Project participants",
    idParam: "project_participant",
    createBody: {
      project_id: 1,
      user_id: 1,
    },
    updateBody: {
      joined_at: "2026-02-12 12:00:00",
    },
    sampleListQuery: {
      project_id: 1,
      per_page: 20,
    },
  }),
  ...createResourceEndpoints({
    resource: "project-invitations",
    group: "Project invitations",
    idParam: "project_invitation",
    createBody: {
      project_id: 1,
      invite_token: "invite-token-001",
      expires_at: "2026-12-31 23:59:59",
    },
    updateBody: {
      invite_token: "invite-token-002",
      expires_at: "2026-12-31 23:59:59",
    },
    sampleListQuery: {
      project_id: 1,
      per_page: 20,
    },
  }),
  {
    id: "project-invitations-accept",
    group: "Project invitations",
    title: "Accept invitation token",
    method: "POST",
    uri: "/project-invitations/accept",
    path: "/project-invitations/accept",
    auth: true,
    description: "Redeem invitation token and join the project as participant.",
    sampleBody: {
      invite_token: "invite-token-001",
    },
  },
  ...createResourceEndpoints({
    resource: "project-snapshots",
    group: "Project snapshots",
    idParam: "project_snapshot",
    createBody: {
      project_id: 1,
      snapshot_hash:
        "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef",
      author_user_id: 1,
      message: "Initial snapshot",
      snapshot_path: "snapshots/initial.zip",
      size_bytes: 4096,
    },
    updateBody: {
      message: "Refined snapshot note",
    },
    sampleListQuery: {
      project_id: 1,
      per_page: 20,
    },
  }),
  ...createResourceEndpoints({
    resource: "admins",
    group: "Admins",
    idParam: "admin",
    createBody: {
      user_id: 1,
    },
    updateBody: {
      user_id: 1,
    },
    adminOnly: true,
  }),
];
